apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "multiverse.saga.dev/v1alpha1",
          "kind": "Trigger",
          "metadata": {
            "name": "trigger-sample"
          },
          "spec": {
            "credentialSecretRef": "my-git-secret",
            "projectId": "my-gcp-projectid",
            "repository": "https://github.com/MyORG/my-repo.git"
          }
        },
        {
          "apiVersion": "multiverse.saga.dev/v1alpha1",
          "kind": "Universe",
          "metadata": {
            "name": "universe-sample"
          },
          "spec": {
            "pr": 439,
            "projectId": "org-playground",
            "repository": "https://github.com/KYRDTeam/org-web.git"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.22.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: preview-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Trigger is the Schema for the triggers API
      displayName: Trigger
      kind: Trigger
      name: triggers.multiverse.saga.dev
      version: v1alpha1
    - description: Universe is the Schema for the universes API
      displayName: Universe
      kind: Universe
      name: universes.multiverse.saga.dev
      version: v1alpha1
  description: A kubernetes operator for preview environment on Google Cloud Platform
  displayName: multiverse
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - multiverse.saga.dev
          resources:
          - triggers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - multiverse.saga.dev
          resources:
          - triggers/finalizers
          verbs:
          - update
        - apiGroups:
          - multiverse.saga.dev
          resources:
          - triggers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - multiverse.saga.dev
          resources:
          - universes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - multiverse.saga.dev
          resources:
          - universes/finalizers
          verbs:
          - update
        - apiGroups:
          - multiverse.saga.dev
          resources:
          - universes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: preview-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: preview-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: asia.gcr.io/org-playground/org/preview-operator:0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: preview-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: preview-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gcp
  - preview-environment
  links:
  - name: Preview Operator
    url: https://preview-operator.domain
  maturity: alpha
  provider:
    name: phuongnd96
  version: 0.0.1
