# permissions for end users to edit universes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: universe-editor-role
rules:
- apiGroups:
  - multiverse.saga.dev
  resources:
  - universes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multiverse.saga.dev
  resources:
  - universes/status
  verbs:
  - get
