# permissions for end users to view universes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: universe-viewer-role
rules:
- apiGroups:
  - multiverse.saga.dev
  resources:
  - universes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multiverse.saga.dev
  resources:
  - universes/status
  verbs:
  - get
