apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: preview-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Trigger is the Schema for the triggers API
      displayName: Trigger
      kind: Trigger
      name: triggers.multiverse.saga.dev
      version: v1alpha1
    - description: Universe is the Schema for the universes API
      displayName: Universe
      kind: Universe
      name: universes.multiverse.saga.dev
      version: v1alpha1
  description: A kubernetes operator for preview environment on Google Cloud Platform
  displayName: multiverse
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gcp
  - preview-environment
  links:
  - name: Preview Operator
    url: https://preview-operator.domain
  maturity: alpha
  provider:
    name: phuongnd96
  version: 0.0.0
