//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Compute) DeepCopyInto(out *Compute) {
	*out = *in
	if in.ComputeNetworks != nil {
		in, out := &in.ComputeNetworks, &out.ComputeNetworks
		*out = make([]ComputeNetworkTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComputeSubnetworks != nil {
		in, out := &in.ComputeSubnetworks, &out.ComputeSubnetworks
		*out = make([]ComputeSubnetworkTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComputeRouters != nil {
		in, out := &in.ComputeRouters, &out.ComputeRouters
		*out = make([]ComputeRouterTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComputeRouterNATs != nil {
		in, out := &in.ComputeRouterNATs, &out.ComputeRouterNATs
		*out = make([]ComputeRouterNATTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Compute.
func (in *Compute) DeepCopy() *Compute {
	if in == nil {
		return nil
	}
	out := new(Compute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeNetworkTemplateSpec) DeepCopyInto(out *ComputeNetworkTemplateSpec) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeNetworkTemplateSpec.
func (in *ComputeNetworkTemplateSpec) DeepCopy() *ComputeNetworkTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeNetworkTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeRouterNATTemplateSpec) DeepCopyInto(out *ComputeRouterNATTemplateSpec) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeRouterNATTemplateSpec.
func (in *ComputeRouterNATTemplateSpec) DeepCopy() *ComputeRouterNATTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeRouterNATTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeRouterTemplateSpec) DeepCopyInto(out *ComputeRouterTemplateSpec) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeRouterTemplateSpec.
func (in *ComputeRouterTemplateSpec) DeepCopy() *ComputeRouterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeRouterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeSubnetworkTemplateSpec) DeepCopyInto(out *ComputeSubnetworkTemplateSpec) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeSubnetworkTemplateSpec.
func (in *ComputeSubnetworkTemplateSpec) DeepCopy() *ComputeSubnetworkTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeSubnetworkTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Container) DeepCopyInto(out *Container) {
	*out = *in
	if in.ContainerClusters != nil {
		in, out := &in.ContainerClusters, &out.ContainerClusters
		*out = make([]ContainerClusterTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContainerNodePools != nil {
		in, out := &in.ContainerNodePools, &out.ContainerNodePools
		*out = make([]ContainerNodePoolTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Container.
func (in *Container) DeepCopy() *Container {
	if in == nil {
		return nil
	}
	out := new(Container)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerClusterTemplateSpec) DeepCopyInto(out *ContainerClusterTemplateSpec) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerClusterTemplateSpec.
func (in *ContainerClusterTemplateSpec) DeepCopy() *ContainerClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNodePoolTemplateSpec) DeepCopyInto(out *ContainerNodePoolTemplateSpec) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNodePoolTemplateSpec.
func (in *ContainerNodePoolTemplateSpec) DeepCopy() *ContainerNodePoolTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerNodePoolTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomObjectMeta) DeepCopyInto(out *CustomObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomObjectMeta.
func (in *CustomObjectMeta) DeepCopy() *CustomObjectMeta {
	if in == nil {
		return nil
	}
	out := new(CustomObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAM) DeepCopyInto(out *IAM) {
	*out = *in
	if in.IAMServiceAccounts != nil {
		in, out := &in.IAMServiceAccounts, &out.IAMServiceAccounts
		*out = make([]IAMServiceAccountTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAM.
func (in *IAM) DeepCopy() *IAM {
	if in == nil {
		return nil
	}
	out := new(IAM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMServiceAccountTemplateSpec) DeepCopyInto(out *IAMServiceAccountTemplateSpec) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMServiceAccountTemplateSpec.
func (in *IAMServiceAccountTemplateSpec) DeepCopy() *IAMServiceAccountTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(IAMServiceAccountTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQL) DeepCopyInto(out *SQL) {
	*out = *in
	if in.SQLInstances != nil {
		in, out := &in.SQLInstances, &out.SQLInstances
		*out = make([]SQLInstanceTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SQLDatabases != nil {
		in, out := &in.SQLDatabases, &out.SQLDatabases
		*out = make([]SQLDatabaseTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQL.
func (in *SQL) DeepCopy() *SQL {
	if in == nil {
		return nil
	}
	out := new(SQL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLDatabaseTemplate) DeepCopyInto(out *SQLDatabaseTemplate) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLDatabaseTemplate.
func (in *SQLDatabaseTemplate) DeepCopy() *SQLDatabaseTemplate {
	if in == nil {
		return nil
	}
	out := new(SQLDatabaseTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLInstanceTemplateSpec) DeepCopyInto(out *SQLInstanceTemplateSpec) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLInstanceTemplateSpec.
func (in *SQLInstanceTemplateSpec) DeepCopy() *SQLInstanceTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(SQLInstanceTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLRestore) DeepCopyInto(out *SQLRestore) {
	*out = *in
	if in.SQLRestores != nil {
		in, out := &in.SQLRestores, &out.SQLRestores
		*out = make([]SQLRestoresTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLRestore.
func (in *SQLRestore) DeepCopy() *SQLRestore {
	if in == nil {
		return nil
	}
	out := new(SQLRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLRestoreSpec) DeepCopyInto(out *SQLRestoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLRestoreSpec.
func (in *SQLRestoreSpec) DeepCopy() *SQLRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(SQLRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLRestoresTemplateSpec) DeepCopyInto(out *SQLRestoresTemplateSpec) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLRestoresTemplateSpec.
func (in *SQLRestoresTemplateSpec) DeepCopy() *SQLRestoresTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(SQLRestoresTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
	if in.StorageBuckets != nil {
		in, out := &in.StorageBuckets, &out.StorageBuckets
		*out = make([]StorageBucketTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBucketTemplateSpec) DeepCopyInto(out *StorageBucketTemplateSpec) {
	*out = *in
	in.CustomObjectMeta.DeepCopyInto(&out.CustomObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBucketTemplateSpec.
func (in *StorageBucketTemplateSpec) DeepCopy() *StorageBucketTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(StorageBucketTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trigger) DeepCopyInto(out *Trigger) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trigger.
func (in *Trigger) DeepCopy() *Trigger {
	if in == nil {
		return nil
	}
	out := new(Trigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Trigger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerList) DeepCopyInto(out *TriggerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Trigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerList.
func (in *TriggerList) DeepCopy() *TriggerList {
	if in == nil {
		return nil
	}
	out := new(TriggerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TriggerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerSpec) DeepCopyInto(out *TriggerSpec) {
	*out = *in
	if in.Respositories != nil {
		in, out := &in.Respositories, &out.Respositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelToDeploymentMap != nil {
		in, out := &in.LabelToDeploymentMap, &out.LabelToDeploymentMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerSpec.
func (in *TriggerSpec) DeepCopy() *TriggerSpec {
	if in == nil {
		return nil
	}
	out := new(TriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerStatus) DeepCopyInto(out *TriggerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerStatus.
func (in *TriggerStatus) DeepCopy() *TriggerStatus {
	if in == nil {
		return nil
	}
	out := new(TriggerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Universe) DeepCopyInto(out *Universe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Universe.
func (in *Universe) DeepCopy() *Universe {
	if in == nil {
		return nil
	}
	out := new(Universe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Universe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniverseList) DeepCopyInto(out *UniverseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Universe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniverseList.
func (in *UniverseList) DeepCopy() *UniverseList {
	if in == nil {
		return nil
	}
	out := new(UniverseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UniverseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniverseSpec) DeepCopyInto(out *UniverseSpec) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
	in.Compute.DeepCopyInto(&out.Compute)
	in.SQL.DeepCopyInto(&out.SQL)
	in.Storage.DeepCopyInto(&out.Storage)
	in.SQLRestore.DeepCopyInto(&out.SQLRestore)
	in.IAM.DeepCopyInto(&out.IAM)
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniverseSpec.
func (in *UniverseSpec) DeepCopy() *UniverseSpec {
	if in == nil {
		return nil
	}
	out := new(UniverseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniverseStatus) DeepCopyInto(out *UniverseStatus) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniverseStatus.
func (in *UniverseStatus) DeepCopy() *UniverseStatus {
	if in == nil {
		return nil
	}
	out := new(UniverseStatus)
	in.DeepCopyInto(out)
	return out
}
